parameters:
#    jhv_payment_service.example.class: JHV\Payment\ServiceBundle\Example

services:
      ### Managers
      jhv_payment_service.manager.plugin:
          class: "%jhv_payment_service.classes.plugin_manager%"
          
      jhv_payment_service.manager.payment_method:
          class     : "%jhv_payment_service.classes.payment_method_manager%"
          arguments : 
              - "@jhv_payment_service.manager.plugin"
              - "%jhv_payment_service.classes.payment_method_class%"
      
      ### Segurança
      jhv_payment_service.security.encrypter:
          class     : "%jhv_payment_service.classes.encrypter%"
          arguments : 
              - "%jhv_payment_service.security.param.secret_key%"
              - "%jhv_payment_service.security.param.cipher%"
              - "%jhv_payment_service.security.param.mode%"
              
      ### Meios de pagamento (FORM)
      jhv_payment.form_type.payment_selector:
          class       : "%jhv_payment_service.classes.payment_selector_type%"
          arguments   : 
              - "@jhv_payment_service.manager.payment_method"
              - "@jhv_payment_service.manager.plugin"
              - "@jhv_payment_service.security.encrypter"
              - "%jhv_payment_service.classes.payment_instruction_class%"
          tags:
              - { name: form.type, alias: payment_selector }
      
      jhv_payment.plugin.credit_card:
          class : "JHV\\Payment\\ServiceBundle\\Plugin\\BlaPlugin"
          tags  :
              - { name: "jhv_payment.plugin_extension" }
              
      credit_card_type:
          class: "JHV\\Payment\\ServiceBundle\\Form\\Type\\CreditCardType"
          tags:
              - { name: form.type, alias: credit_card }
              - { name: "jhv_payment.payment_method", plugin: "bla_plugin" }