services:  
      ### Managers
      jhv_payment_service.manager.plugin:
          class: "%jhv_payment_service.classes.plugin_manager%"
          
      jhv_payment_service.manager.payment_method:
          class     : "%jhv_payment_service.classes.payment_method_manager%"
          arguments : 
              - "@jhv_payment_service.manager.plugin"
              - "%jhv_payment_service.classes.payment_method_class%"
      
      ### Segurança
      jhv_payment_service.security.encrypter:
          class     : "%jhv_payment_service.classes.encrypter%"
          arguments : 
              - "%jhv_payment_service.security.param.secret_key%"
              - "%jhv_payment_service.security.param.cipher%"
              - "%jhv_payment_service.security.param.mode%"
              
      ### Meios de pagamento (FORM)
      jhv_payment.form_type.payment_selector:
          class       : "%jhv_payment_service.classes.payment_selector_type%"
          arguments   : 
              - "@jhv_payment_service.manager.payment_method"
              - "@jhv_payment_service.manager.plugin"
              - "@jhv_payment_service.security.encrypter"
              - "%jhv_payment_service.classes.payment_instruction_class%"
          tags:
              - { name: form.type, alias: payment_selector }
              
      ### Form Factory
      jhv_payment_service.factory.payment_process:
          class       : "%jhv_payment_service.classes.payment_selector_factory%"
          arguments   : ["@form.factory", "@jhv_payment.form_type.payment_selector"]
          
      ### Twig extension
      jhv_payment_service.twig_extension.payment_process:
          class       : "%jhv_payment_service.classes.twig_extension%"
          arguments   : ["@service_container", "%jhv_payment_service.template.default_template%"]
          tags        :
              - { name: "twig.extension" }